	# Site settings
baseurl = "http://diegoscmo.github.io/public/"
languageCode = "en-us"
title = "Diego S. Montero"
theme = "hugo-agency"

# # http://diegoscmo.github.io/public/
# # 127.0.0.1:1313


[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Diego Schmitt Montero"
	description = "Mechanical Engineer, Engineer, WEG, Wind Turbines, BAJA"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "your@email.com"


	# Navigation
	[params.navigation]
		brand = "Diego S. Montero - Mechanical Engineer"
#D		services = "Services"
#D		portfolio = "Portfolio"
		about = "My trajectory"
		team = "About me"
#D		contact = "Contact"


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Welcome To My Page!"
		subtitle = "It is nice to meet you :)"
		buttonText = "Find out a little more about me!"


	# Services section
	[params.services]
		title = "Services"
		subtitle = "Lorem ipsum dolor sit amet consectetur."

		[[params.services.list]]
			icon = "fa-shopping-cart"
			title = "E-Commerce"
			description = "Lorem "

		[[params.services.list]]
			icon = "fa-laptop"
			title = "Responsive Design"
			description = "Lorem"

		[[params.services.list]]
			icon = "fa-lock"
			title = "Web"
			description = "Lorem "


	# Portfolio section
	[params.portfolio]
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Portfolio"
		subtitle = "Lorem ipsum dolor sit amet consectetur."

		[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"


    # About section
	[params.about]
		title = "My Trajectory"
		subtitle = "A brief timeline of what I have been doing so far *(I hope to get into more details of relevant projects as I further develop this page).*"
		endpoint = "What should be <br>next?<br>"

		# The events will be listed from the top to the bottom.
		# All images are stored under 'static/img/about'.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			date = "July 2009"
			title = "Mechanical Engineering 101"
			description = "Started a Mechanical Engineering course at UDESC (Universidade do Estado de Santa Catarina). Understanding how things works and the habit of taking things apart as a kid were my two main drivers towards engineering."

		[[params.about.events]]
			img = "2.jpg"
			date = "March 2010"
			title = "Velociraptor Baja-SAE"
			description = "I began participating in the Baja-SAE Velociraptor team. The focus of the project is to design and build an off-road vehicle for competitions between universities. Good place to learn a lot about automotive engineering, project managing and teamwork."

		[[params.about.events]]
			img = "3.jpg"
			date = "December 2010"
			title = "Summer Work/Travel Exchange"
			description = "Since I was a kid I have always enjoyed the video games, since at that time none of the current games were in Portuguese, my older brother gave me an English dictionary. With that, I learned how to write and read in English around 10. Going abroad was a fast way to finally practice and learn how to speak. I have spent three months working in a restaurant at Nascar Sports Grille in Orlando/Florida."

		[[params.about.events]]
			img = "4.jpg"
			date = "September 2011"
			title = "Own Baja Project"
			description = "After learning a lot in the Baja team, I have decided to design and build my own. Together with my older brother (also a Mechanical Engineer), we did just that. We have designed an off-road vehicle from scratch and build in our garage, my brother used the project as his Graduation Thesis later on, we took almost a year and a half of weekends to get it running *(Hope to go into more depth of the designing process here later on)*."

		[[params.about.events]]
			img = "5.jpg"
			date = "December 2013"
			title = "Thesis, Particle Swarm Truss Optimization"
			description = "Time to work on my thesis! I fell in love with optimization the moment that my professor started explaining it to me. Since I had a lot of trouble designing the Truss-like chassis of our Baja Project, Truss optimization was a natural choice for a thesis. I had a lot of fun working on this and learned a lot about Optimization and Finite Elements Method, which are my two main areas of interest together with Structural calculations."

[[params.about.events]]
			img = "6.jpg"
			date = "February 2014"
			title = "Internship, WEG - Wind Power"
			description = "I was lucky enough to get a position in the brand new Wind Power department at WEG. Wind Turbines are an awesome product to learn and work with. I landed a position in Supply Chain and did a little bit of everything in there as an intern."

[[params.about.events]]
			img = "7.jpg"
			date = "July 2014"
			title = "Graduation and Job!"
			description = "Finally, I have graduated! In the same month, I got an effective position at WEG, still working with Wind Turbines but now more focused on Developing Suppliers for components of a new Wind Turbine (the AGW3.3). I am still exponentially learning about all sorts of critical components of a Gearless Wind Turbine, to name a few: Pitch System, Slipring, Slewing Bearings, Cooling System, Pitch and Yaw Gearboxes, Structural Castings, and the list goes on..."

			[[params.about.events]]
			img = "8.jpg"
			date = "August 2015"
			title = "Began my Master's Degree"
			description = "Began a Masters course in *Project, Analysis and Optimization of Mechanical Systems*. Since I am in the first semester with just a couple of classes each week I still do not know what I will be working on for a thesis. I am hoping to use this knowledge in a more technical position later on."

			[[params.about.events]]
			img = "9.jpg"
			date = "September 2015"
			title = "Nemo Project"
			description = "Now I am together with two other engineers to design and build a Hydrofoil Bicycle. We are doing this mostly for fun right now and we hope to get that done in a year, I will try to record part of the process in here."

	# Team section
	[params.team]
		title = "About me"
		subtitle = ""

		description ="Hey, I hope that by know you already know my name and that I am a Brazilian Mechanical Engineer, currently working with Wind Turbines at WEG. My trajectory above says pretty much all you need to know about me professionaly. :"

description1 = "If you would like to contact me for more information, or if there is a project that you think I might me interested in, please click the social media links on this page or refer to the contact information in my *Curriculum Vitae*"

description2 = "[CV - Portuguese version] (http://diegoscmo.github.io/Diego_Schmitt_Montero-CV_PT.pdf);"
description3 = "[CV - English version] (http://diegoscmo.github.io/Diego_Schmitt_Montero-CV_ENG.pdf);"
description4 = "I am still working on this page, I hope to be updating with further details on my projects. Thanks for checking me out, have a nice one! ;)"




		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "1.jpg"
			name = "Diego Schmitt Montero"
			position = "Mechanical Engineer"
			social = [
			#D	["fa-twitter", "#"],
				["fa-facebook", "https://www.facebook.com/diegoscmo"],
				["fa-linkedin", "http://br.linkedin.com/in/diegoscmo"]
			]

	# Client section
	# All the clients' logos are stored under 'static/img/logos'.
	# Replace them with your clients's logos.
	[[params.clients]]
		logo = "envato.jpg"
		link = "#"

	[[params.clients]]
		logo = "designmodo.jpg"
		link = "#"

	[[params.clients]]
		logo = "themeforest.jpg"
		link = "#"

	[[params.clients]]
		logo = "creative-market.jpg"
		link = "#"


	# Contact section
	[params.contact]
		title = "Contact me"
		subtitle  = "Lorem ipsum dolor sit amet consectetur."
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
		copyright = "Diego Schmitt Montero - 2015"

	#D	[[params.footer.social]]
	#D		icon = "fa-twitter"
	#D		link = "#"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "https://www.facebook.com/diegoscmo"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "http://br.linkedin.com/in/diegoscmo"

		[[params.footer.quicklinks]]
			text = "Privacy Policy"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Terms of Use"
			link = "#"
